import type {Metadata} from 'next';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import {projects,projectById} from '@/content/projects';
import {Arrow} from '@/components/v2/Chrome';
import {ProjectVisual} from '@/components/v2/ProjectVisual';
export function generateStaticParams(){return projects.map(p=>({slug:p.id}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const p=projectById(slug);return p?{title:p.name,description:p.oneLiner,alternates:{canonical:`/work/${p.id}/`}}:{}}
export default async function Work({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=projectById(slug);if(!p)notFound();const next=projects[(projects.findIndex(x=>x.id===p.id)+1)%projects.length];const kind=p.id.includes('verification')?'research':p.id.includes('gantt')?'gantt':p.id==='hermesfix'?'hermes':p.id==='mergelearn'?'learning':p.id==='strategy-agentic-platform'?'agents':null;return <article className="container page-content case-study"><Link className="text-link back-link" href="/#work"><span aria-hidden="true">←</span> Back to work</Link><header className="case-heading"><div className="eyebrow">{p.org} <span className="separator">/</span> {p.status}</div><h1>{p.name.replaceAll('Multi-Agent','Multi‑Agent')}</h1><p>{p.oneLiner}</p><div className="case-facts"><div><span>MY ROLE</span><p>{p.role}</p></div><div><span>PERIOD</span><p>{p.period}</p></div><div><span>STACK</span><p>{p.stack.join(' · ')}</p></div></div></header>{kind&&<div className="case-visual"><ProjectVisual kind={kind}/></div>}<div className="case-body"><aside><p className="eyebrow">IN THIS CASE STUDY</p><a href="#problem">The problem</a><a href="#approach">The approach</a><a href="#contribution">My contribution</a>{p.technical&&<a href="#decisions">Technical decisions</a>}{p.links.length>0&&<div className="case-resources"><span className="eyebrow">RESOURCES</span>{p.links.map(l=><a href={l.href} key={l.href}>{l.label} <Arrow diagonal/></a>)}</div>}</aside><div className="case-prose"><section id="problem"><span className="eyebrow">01 / CONTEXT</span><h2>The problem.</h2><p>{p.problem}</p></section><section id="approach"><span className="eyebrow">02 / APPROACH</span><h2>How I approached it.</h2><ol className="approach-list">{p.approach.map((a,i)=><li key={a}><span>0{i+1}</span><p>{a}</p></li>)}</ol></section><section id="contribution"><span className="eyebrow">03 / CONTRIBUTION</span><h2>What came out of the work.</h2>{p.contribution.map(c=><p key={c}>{c}</p>)}{p.kind==='research'&&<div className="scope-note">Scope of the guarantee: expected tuple-level false discovery rate relative to the strong judge’s labels, under exchangeability of calibration and deployment data. This is not a correctness guarantee for each answer. Model or domain changes require recalibration; the numbers above describe the reported evaluation.</div>}</section>{p.technical&&<section id="decisions"><span className="eyebrow">04 / ENGINEERING NOTES</span><h2>The decisions that mattered.</h2>{p.technical.map(t=><div className="technical-note" key={t.decision}><h3>{t.decision}</h3><p>{t.rationale}</p></div>)}</section>}</div></div><Link className="next-project" href={`/work/${next.id}/`}><div><span className="eyebrow">NEXT CASE STUDY</span><h2>{next.name}</h2></div><Arrow/></Link></article>}
