'use client';
import {useState} from 'react';
import {publicationsByRecency,allTopics,toBibTeX} from '@/content/publications';
import {Arrow} from './Chrome';
export default function PaperLibrary(){
 const [year,setYear]=useState('All');const [topic,setTopic]=useState('All topics');const [copied,setCopied]=useState('');const [fallback,setFallback]=useState('');
 const filtered=publicationsByRecency.filter(p=>(year==='All'||String(p.year)===year)&&(topic==='All topics'||p.topics.some(t=>t===topic)));
 async function copy(id:string){const p=publicationsByRecency.find(p=>p.id===id)!;try{await navigator.clipboard.writeText(toBibTeX(p));setCopied(id);setFallback('');}catch{setFallback(id);setCopied('');}}
 return <><div className="library-toolbar"><div className="filter-years" role="group" aria-label="Filter publications by year">{['All','2026','2025','2024'].map(y=><button key={y} onClick={()=>setYear(y)} aria-pressed={year===y}>{y}</button>)}</div><label className="topic-select"><span className="visually-hidden">Filter by topic</span><select value={topic} onChange={e=>setTopic(e.target.value)}><option>All topics</option>{allTopics.map(t=><option key={t}>{t}</option>)}</select></label></div><p className="result-count" aria-live="polite">{filtered.length} {filtered.length===1?'publication':'publications'}{topic!=='All topics'?` · ${topic}`:''}</p><div className="library-list">{filtered.map(p=><article className="library-paper" key={p.id}><div className="library-side"><span>{p.year}</span><span className="paper-type">{p.kind}</span></div><div className="library-main"><div className="library-venue">{p.venueShort}</div><h2><a href={p.links[0].href}>{p.title}</a></h2><p className="authors">{p.authors.join(' · ')}</p><p className="paper-summary">{p.summary}</p><div className="paper-actions">{p.links.map(l=><a href={l.href} key={l.href}>{l.label} <Arrow diagonal/></a>)}<button onClick={()=>copy(p.id)}>{copied===p.id?'Copied ✓':'Copy citation'}</button><span className="visually-hidden" role="status">{copied===p.id?'Citation copied to clipboard':''}</span></div>{fallback===p.id&&<div className="citation-fallback"><label htmlFor={`citation-${p.id}`}>Select and copy this citation</label><textarea id={`citation-${p.id}`} readOnly value={toBibTeX(p)} onFocus={e=>e.target.select()}/></div>}<details className="paper-details"><summary>Read {p.abstract?'abstract':'research summary'} <span aria-hidden="true">+</span></summary><p>{p.abstract||p.summary}</p><div className="topic-tags">{p.topics.map(t=><span key={t}>{t}</span>)}</div></details></div></article>)}</div>{filtered.length===0&&<div className="empty-state"><h2>No papers in this combination.</h2><p>Try a different year or topic.</p><button className="button secondary" onClick={()=>{setYear('All');setTopic('All topics')}}>Clear filters</button></div>}</>
}
