'use client';
import {useRef,useState} from 'react';
import {rounds} from '@/content/quorum';
import {Arrow} from './Chrome';
import Link from 'next/link';
const lesson=[
 'The majority is right in this example. But the vote count alone does not establish that the answers are independent.',
 'All five agents confuse height above sea level with distance from Earth’s centre. Their confidence repeats one shared mistake.',
 'The minority supplies the relevant comparison: rotation versus orbit. The evidence matters more than the number of votes.'
];
export default function QuorumLab(){const [step,setStep]=useState(0);const [choice,setChoice]=useState<'trust'|'check'|null>(null);const [finished,setFinished]=useState(false);const heading=useRef<HTMLHeadingElement>(null);const feedback=useRef<HTMLDivElement>(null);const r=rounds[step];const yes=r.agents.filter(a=>a.verdict==='supported').length;const majority=yes>=3?'supported':'refuted';const right=majority===r.truth;
 function decide(value:'trust'|'check'){setChoice(value);requestAnimationFrame(()=>feedback.current?.focus())}
 function next(){if(step===rounds.length-1){setFinished(true)}else{setStep(step+1);setChoice(null)}requestAnimationFrame(()=>heading.current?.focus())}
 function restart(){setStep(0);setChoice(null);setFinished(false);requestAnimationFrame(()=>heading.current?.focus())}
 if(finished)return <div className="lab-complete"><div className="eyebrow">THE TAKEAWAY</div><h2 ref={heading} tabIndex={-1}>A chorus can still<br/>be an echo.</h2><p>Agreement is useful only in context. Correlated errors, weak evidence and high confidence can travel together.</p><p>These scripted examples illustrate the motivation for my research. The paper goes further: it calibrates a decision threshold with an expected false discovery rate bound across queries.</p><div className="inline-links"><Link className="button primary" href="/work/certified-multi-agent-verification/">Explore the research <Arrow/></Link><button className="button secondary" onClick={restart}>Try again</button></div></div>;
 return <div className="quorum-lab"><div className="lab-progress"><span className="eyebrow">CLAIM 0{step+1} / 03</span><div aria-hidden="true">{rounds.map((_,i)=><span className={i<=step?'active':''} key={i}/>)}</div></div><h2 ref={heading} tabIndex={-1}>{r.claim}</h2><div className="ensemble-summary"><span>{Math.max(yes,5-yes)}/5 <small>agents {majority==='supported'?'support':'reject'} this claim</small></span><span>{Math.round(r.agents.reduce((t,a)=>t+a.confidence,0)/5*100)}% <small>mean confidence</small></span></div><div className="agent-responses">{r.agents.map((a,i)=><details key={a.id}><summary><span className={`agent-avatar family-${a.lineage==='α'?'a':a.lineage==='β'?'b':'c'}`}>{i+1}</span><span className="agent-identity">Agent {i+1}<small>Source family {a.lineage==='α'?'A':a.lineage==='β'?'B':'C'}</small></span><span className="agent-verdict">{a.verdict==='supported'?'Supports':'Rejects'}<small>{Math.round(a.confidence*100)}% confident</small></span><span className="expand-sign" aria-hidden="true">+</span></summary><p>{a.reasoning}</p></details>)}</div>{choice===null?<div className="lab-decision"><p>Would you trust the majority?</p><div><button className="button primary" onClick={()=>decide('trust')}>Trust the majority <Arrow/></button><button className="button secondary" onClick={()=>decide('check')}>Check the evidence</button></div></div>:<div ref={feedback} tabIndex={-1} className={`lab-feedback ${right?'supported':'refuted'}`} role="region" aria-label="Evidence and result"><span className="eyebrow">{choice==='check'?'EVIDENCE CHECK':'THE REVEAL'}</span><h3>{right?'The majority is right this time.':'The majority is wrong.'}</h3><p>{r.truthNote}</p><p>{lesson[step]}</p><button className="button primary" onClick={next}>{step===2?'See the takeaway':'Next claim'} <Arrow/></button></div>}</div>
}
