import type { Metadata, Viewport } from "next";
import { Newsreader, Instrument_Sans, IBM_Plex_Mono } from "next/font/google";
import "./globals.css";
import { SiteHeader } from "@/components/chrome/SiteHeader";
import { SiteFooter } from "@/components/chrome/SiteFooter";
import { site } from "@/content/site";
import { publications } from "@/content/publications";
import { roles, education } from "@/content/experience";

/**
 * Font loading is deliberately narrow. Every extra weight is another file on the
 * critical path, and the design uses exactly these: regular and medium serif with a
 * regular italic, two sans weights, one mono.
 */
const newsreader = Newsreader({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-newsreader",
  style: ["normal", "italic"],
  weight: ["400", "500"],
});

const instrumentSans = Instrument_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-instrument-sans",
  weight: ["400", "500"],
});

const plexMono = IBM_Plex_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-plex-mono",
  weight: ["400"],
});

const description =
  "Adam Kostka is an AI engineer at Strategy (NASDAQ: MSTR) and a published researcher on multi-agent LLM reliability — agreement, uncertainty and hallucination risk. Eight peer-reviewed papers, including UAI 2026.";

export const metadata: Metadata = {
  metadataBase: new URL(site.url),
  title: {
    default: `${site.name} — AI Engineer & Multi-Agent Systems Researcher`,
    template: `%s — ${site.name}`,
  },
  description,
  keywords: [
    "Adam Kostka",
    "AI engineer",
    "multi-agent systems",
    "LLM agents",
    "uncertainty quantification",
    "hallucination",
    "multi-agent reliability",
    "Warsaw University of Technology",
  ],
  authors: [{ name: site.name, url: site.url }],
  creator: site.name,
  alternates: { canonical: "/" },
  openGraph: {
    /*
     * A real PNG in /public rather than a generated route.
     *
     * The generated `opengraph-image` route emits a file with no extension, which a
     * static host serves as application/octet-stream — social scrapers then refuse it.
     * The card is regenerated by restoring scripts/og/opengraph-image.tsx to
     * src/app/, running `npm run build`, and copying `out/opengraph-image` to
     * `public/og.png`. It only changes when the design does.
     */
    images: [
      {
        url: "/og.png",
        width: 1200,
        height: 630,
        alt: "Adam Kostka — AI engineer and multi-agent systems researcher",
      },
    ],
    type: "profile",
    title: `${site.name} — AI Engineer & Multi-Agent Systems Researcher`,
    description,
    url: site.url,
    siteName: site.name,
    locale: "en_GB",
    firstName: "Adam",
    lastName: "Kostka",
  },
  twitter: {
    card: "summary_large_image",
    images: ["/og.png"],
    title: `${site.name} — AI Engineer & Multi-Agent Systems Researcher`,
    description,
  },
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true, "max-image-preview": "large" },
  },
  category: "technology",
};

export const viewport: Viewport = {
  themeColor: "#f6f4ef",
  colorScheme: "light",
  width: "device-width",
  initialScale: 1,
};

/**
 * JSON-LD. Only facts already present in the content modules — the structured data
 * must never assert more than the visible page does.
 */
function structuredData() {
  const current = roles[0];
  return {
    "@context": "https://schema.org",
    "@type": "Person",
    name: site.name,
    url: site.url,
    email: `mailto:${site.email}`,
    jobTitle: "AI Engineer",
    identifier: {
      "@type": "PropertyValue",
      propertyID: "ORCID",
      value: `https://orcid.org/${site.orcid}`,
    },
    address: { "@type": "PostalAddress", addressLocality: "Warsaw", addressCountry: "PL" },
    worksFor: { "@type": "Organization", name: current.org },
    alumniOf: education.map((e) => ({
      "@type": "CollegeOrUniversity",
      name: e.institution,
    })),
    knowsAbout: [
      "Multi-agent systems",
      "Large language model agents",
      "Uncertainty quantification",
      "Software engineering",
    ],
    sameAs: [
      site.links.github.href,
      site.links.scholar.href,
      site.links.linkedin.href,
      `https://orcid.org/${site.orcid}`,
    ],
    subjectOf: publications.map((p) => ({
      "@type": "ScholarlyArticle",
      name: p.title,
      datePublished: String(p.year),
      author: p.authors.map((a) => ({ "@type": "Person", name: a })),
      isPartOf: { "@type": "PublicationEvent", name: p.venue },
      ...(p.links[0] ? { url: p.links[0].href } : {}),
    })),
  };
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    /*
     * The font variables must live on <html>, not <body>.
     *
     * Tailwind declares --font-serif on :root as `var(--font-newsreader), …`.
     * Custom-property substitution resolves against the *declaring* element, so if
     * --font-newsreader is only defined on <body>, the :root declaration is
     * guaranteed-invalid and computes to nothing — every heading silently falls back
     * to the system stack. Putting them on <html> makes :root self-consistent.
     */
    <html
      lang="en"
      className={`${newsreader.variable} ${instrumentSans.variable} ${plexMono.variable}`}
    >
      <body className="antialiased">
        <a href="#main" className="sr-only-focusable">
          Skip to content
        </a>
        <SiteHeader />
        <main id="main">{children}</main>
        <SiteFooter />
        <script
          type="application/ld+json"
          // eslint-disable-next-line react/no-danger
          dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData()) }}
        />
      </body>
    </html>
  );
}
